version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: minha-app-php
    volumes:
      - .:/var/www/html
    networks:
      - minha-app-net

  web:
    image: nginx:alpine
    container_name: minha-app-nginx
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./deploy/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - minha-app-net

networks:
  minha-app-net:
    driver: bridge
